# Generated by Django 5.0.1 on 2024-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_footer',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
